services:
  - type: web
    name: task-management-app
    env: node
    buildCommand: npm install --legacy-peer-deps && cd task-management-app && NODE_OPTIONS=--max-old-space-size=4096 npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
      - key: MONGODB_URI
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        fromService:
          name: task-management-app
          type: web
          property: url 