services:
  - type: web
    name: task-management-app
    env: node
    plan: free
    buildCommand: cd task-management-app && npm install --legacy-peer-deps && npm run build
    startCommand: cd task-management-app && PORT=10000 NODE_ENV=production node express-server.js
    healthCheckPath: /health
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
      - key: MONGODB_URI
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        fromService:
          name: task-management-app
          type: web
          property: url 